name:                tvqbh
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- aeson
- transformers
- req
- unordered-containers
- mtl
- persistent
- persistent-template
- persistent-sqlite
- unliftio-core
- text
- monad-logger
- time
- http-client
- http-types
- utf8-string
- containers
- servant-server
- servant-auth-server
- pwstore-fast
- wai
- warp
- bytestring

library:
  source-dirs: src

executables:
  tvqbh-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tvqbh

tests:
  tvqbh-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tvqbh
    - QuickCheck
    - quickcheck-instances
    - generic-random
    - directory
    - HUnit
